In [5]:
# Write a function so that the columns of the output matrix are powers of the input vector.  
# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
# the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

# This prablem statement has been done using using Vander function and also my own function.

In [6]:
# NP Vander with Array
import numpy as np
x = np.array([1, 2, 3, 4, 5])
N = 5
np.vander(x, N)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [7]:
# NP Vander with Power (N-1-i)
np.column_stack([x**(N-1-i) for i in range(N)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [8]:
# NP Vander with Increasing False
x = np.array([1, 2, 3, 4, 5])
np.vander(x, increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [9]:
# NP Vander with Increasing True
np.vander(x, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [10]:
# Function similar to Increasing is True
import numpy as np

def vander_mat(v):
    z = []
    x=0
    for i in range(v):
        x=x+1
        for j in range(v):
            a=z.append(x**j)
            k=np.array(z)
    return k.reshape(v,v)
vander_mat(5)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [11]:
# Function similar to Increasing is False
def vander_mat(v):
    z = []
    x=0
    for i in range(v):
        x=x+1
        for j in range(v):
            a=z.append(x**j)
            k=np.array(z)
    h = k.reshape(v,v)
    return np.fliplr(h)
vander_mat(5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])